In [1]:
import pandas as pd

In [2]:
#清洗测试集
df_test = pd.read_excel("C:/Users/20851/Desktop/2022年MathorCup大数据竞赛-赛道B初赛/清洗后语音满意度测试数据.xlsx")
df_train = pd.read_excel("C:/Users/20851/Desktop/2022年MathorCup大数据竞赛-赛道B初赛/清洗后语音满意度数据.xlsx")

In [3]:
# #先清洗测试集
# #删除8列无用数据
# del df_test['用户id']
# del df_test['用户描述']
# del df_test['用户描述.1']
# del df_test['终端品牌']
# del df_test['终端品牌类型']
# del df_test['性别']
# del df_test['是否投诉']
# del df_test['是否不限量套餐到达用户']

# df_test.iloc[:,0] = df_test.iloc[:,0].map({1:1,2:0})
# for i in range(1,16):
#     df_test.iloc[:,i] = df_test.iloc[:,i].map({-1:0,1:1,2:1,3:1,4:1,5:1,6:1,7:1,98:1})
# df_test.iloc[:,19] = df_test.iloc[:,19].map({'2G':2,'4G':4,'5G':5})
# for i in ['是否关怀用户', '是否4G网络客户（本地剔除物联网）', '是否5G网络客户']:
#     df_test[i] = df_test[i].fillna(0).map({0:0,'是':1,'否':0})#29,30,33,45,46
# df_test['客户星级标识'] = df_test['客户星级标识'].fillna(0).map({'未评级':0,'准星':0, '一星':1,'二星':2,'三星':3, '白金卡':4, '钻石卡':5, '银卡':6,'金卡':7})
# #保存成excel文件
# df_test.to_excel("C:/Users/20851/Desktop/2022年MathorCup大数据竞赛-赛道B初赛/清洗后语音满意度测试数据.xlsx",index=None)


In [4]:
c_test = list(df_test.columns)
c_train = list(df_train.columns)

all_columns = []
#获取两者都有的列
for i in c_test:
    if i in c_train:#当i在两边都有时
        all_columns.append(i)
print(all_columns)
print(len(all_columns))
print(list(df_train.columns))


['是否遇到过网络问题', '居民小区', '办公室', '高校', '商业街', '地铁', '农村', '高铁', '其他，请注明', '手机没有信号', '有信号无法拨通', '通话过程中突然中断', '通话中有杂音、听不清、断断续续', '串线', '通话过程中一方听不见', '其他，请注明.1', '脱网次数', 'mos质差次数', '未接通掉话次数', '4\\5G用户', '是否关怀用户', '套外流量（MB）', '是否4G网络客户（本地剔除物联网）', '套外流量费（元）', '外省语音占比', '语音通话-时长（分钟）', '省际漫游-时长（分钟）', '当月ARPU', '当月MOU', '前3月ARPU', '前3月MOU', '外省流量占比', 'GPRS总流量（KB）', 'GPRS-国内漫游-流量（KB）', '是否5G网络客户', '客户星级标识']
36
['语音通话整体满意度', '网络覆盖与信号强度', '语音通话清晰度', '语音通话稳定性', '是否遇到过网络问题', '居民小区', '办公室', '高校', '商业街', '地铁', '农村', '高铁', '其他，请注明', '手机没有信号', '有信号无法拨通', '通话过程中突然中断', '通话中有杂音、听不清、断断续续', '串线', '通话过程中一方听不见', '其他，请注明.1', '脱网次数', 'mos质差次数', '未接通掉话次数', '重定向次数', '重定向驻留时长', '家宽投诉', '资费投诉', '4\\5G用户', '语音方式', '是否关怀用户', '是否去过营业厅', 'ARPU（家庭宽带）', '套外流量（MB）', '是否4G网络客户（本地剔除物联网）', '套外流量费（元）', '外省语音占比', '语音通话-时长（分钟）', '省际漫游-时长（分钟）', '当月ARPU', '当月MOU', '前3月ARPU', '前3月MOU', '外省流量占比', 'GPRS总流量（KB）', 'GPRS-国内漫游-流量（KB）', '是否5G网络客户', '是否实名登记用户', '客户星级标识', '当月欠费金额', '前第3个月欠费金额']


In [5]:
#准备数据集
train_X = df_train.loc[:,all_columns].values
train_Y1 = df_train.loc[:,'语音通话整体满意度'].values
train_Y2 = df_train.loc[:,'网络覆盖与信号强度'].values
train_Y3 = df_train.loc[:,'语音通话清晰度'].values
train_Y4 = df_train.loc[:,'语音通话稳定性'].values

test_X = df_test.loc[:,all_columns].values

# 将数据分为训练集和测试集
from sklearn.model_selection import train_test_split
import numpy as np

# X_train, X_test, y_train, y_test = train_test_split(train_X,
#                                                     train_Y4,
#                                                     test_size=0.1,
#                                                     random_state=0)

# 训练随机森林解决回归问题
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeClassifier

def train(regressor, X_train, y_train):
     
      regressor.fit(X_train, y_train)
      # X_test = X_train[0:500,:]
      # y_test = y_train[0:500]
      y_pred = regressor.predict(X_train)

      y_pred = np.round(y_pred)
      y_test = np.round(y_train).astype(np.float64)

      print(y_pred[0:10])
      print(y_test[0:10])

      print(np.sum(y_pred==y_test))
      print(y_pred.shape[0])

      # 评估回归性能
      from sklearn import metrics


      print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
      print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
      print('Root Mean Squared Error:',
      np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
      return y_pred



In [6]:
regressor1 = DecisionTreeClassifier()
y1 = train(regressor1,X_train=train_X,y_train=train_Y1)

[10  2 10  6  5  7  8 10 10 10]
[10.  2. 10.  6.  5.  7.  8. 10. 10. 10.]
5427
5427
Mean Absolute Error: 0.0
Mean Squared Error: 0.0
Root Mean Squared Error: 0.0


In [7]:
regressor1 = RandomForestRegressor(n_estimators=200, random_state=1,max_depth=7,oob_score=True,criterion='absolute_error',bootstrap=True)
y1 = train(regressor1,X_train=train_X,y_train=train_Y1)

[ 8.  7. 10.  8.  7.  8.  9. 10. 10.  9.]
[10.  2. 10.  6.  5.  7.  8. 10. 10. 10.]
2843
5427
Mean Absolute Error: 0.9845218352681039
Mean Squared Error: 3.3795835636631657
Root Mean Squared Error: 1.8383643718433964


In [8]:
regressor2 = RandomForestRegressor(n_estimators=200, random_state=1,max_depth=7,oob_score=True,criterion='absolute_error',bootstrap=True)
y2 = train(regressor2,X_train=train_X,y_train=train_Y2)

In [ ]:
regressor3 = RandomForestRegressor(n_estimators=100, random_state=1,max_depth=7,oob_score=True,criterion='absolute_error',bootstrap=True)
y3 = train(regressor3,X_train=train_X,y_train=train_Y3)

In [ ]:
regressor4 = RandomForestRegressor(n_estimators=100, random_state=1,max_depth=7,oob_score=True,criterion='absolute_error',bootstrap=True)
y4 = train(regressor4,X_train=train_X,y_train=train_Y4)

In [ ]:
#可视化
from six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
import os

# 执行一次
os.environ['PATH'] = os.environ['PATH']+';'+"D:/Graphviz/bin/"
dot_data1 = StringIO()
export_graphviz(regressor1.estimators_[0],
                out_file=dot_data1)
graph = pydotplus.graph_from_dot_data(dot_data1.getvalue())
graph.write_png('tree1.png')
Image(graph.create_png())

dot_data2 = StringIO()
export_graphviz(regressor2.estimators_[0],
                out_file=dot_data2)
graph = pydotplus.graph_from_dot_data(dot_data2.getvalue())
graph.write_png('tree2.png')
Image(graph.create_png())

dot_data3 = StringIO()
export_graphviz(regressor3.estimators_[0],
                out_file=dot_data3)
graph = pydotplus.graph_from_dot_data(dot_data3.getvalue())
graph.write_png('tree3.png')
Image(graph.create_png())

dot_data4 = StringIO()
export_graphviz(regressor4.estimators_[0],
                out_file=dot_data4)
graph = pydotplus.graph_from_dot_data(dot_data4.getvalue())
graph.write_png('tree4.png')
Image(graph.create_png())

In [ ]:
pd.concat([y1,y2,y3,y4],axis=1,ignore_index=False)